"""test

Revision ID: 0318a7610708
Revises: 63260246ff45
Create Date: 2020-06-09 21:06:20.866625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0318a7610708'
down_revision = '63260246ff45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_information',
    sa.Column('usr_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('pwd', sa.VARCHAR(length=100), nullable=True),
    sa.Column('rank', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('usr_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_information')
    # ### end Alembic commands ###
