"""databse change

Revision ID: 284e2fd16e55
Revises: ef0422c719e3
Create Date: 2020-06-15 20:28:02.024824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284e2fd16e55'
down_revision = 'ef0422c719e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
