"""user_info table now has rank

Revision ID: 63260246ff45
Revises: f124d03fec6e
Create Date: 2020-06-09 20:23:59.914639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63260246ff45'
down_revision = 'f124d03fec6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_information')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_information',
    sa.Column('usr_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('First_Name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Last_Name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('pwd', mysql.VARCHAR(length=99), nullable=False),
    sa.PrimaryKeyConstraint('usr_name'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('usr_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('pwd', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('usr_name'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
