"""user updated removed id

Revision ID: 90ae90daa181
Revises: 8bcc4baddca9
Create Date: 2020-06-16 21:16:34.298459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90ae90daa181'
down_revision = '8bcc4baddca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='users')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('id', 'users', ['id'], unique=True)
    # ### end Alembic commands ###
