"""add ilo score column

Revision ID: ef0422c719e3
Revises: d31866a7ec4c
Create Date: 2020-06-15 20:21:53.804897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0422c719e3'
down_revision = 'd31866a7ec4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ilo', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ilo')
    # ### end Alembic commands ###
