"""test2

Revision ID: fbac2cd4c501
Revises: 0318a7610708
Create Date: 2020-06-09 21:07:24.551056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbac2cd4c501'
down_revision = '0318a7610708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_information', sa.Column('test', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_information', 'test')
    # ### end Alembic commands ###
